### ISSUE TITLE
Ajouter un bouton Retour au choix des parcours

### ISSUE THREAD

**Issue by Umi130** [Umi130/Passion-IA#1]

**Comment by Umi130** [comment]
En utilisant l'image de la croix bleu à mettre en haut à droite

**Comment by julesbonnard** [comment]
Ajouté : https://github.com/Umi130/Passion-IA/commit/0d014cd23040a4b0d7e7777d3d449d8e1cdaa479 et https://github.com/Umi130/Passion-IA/commit/7398e5aba3b0abce35594d3cd95303c5f2e5e22b

Reste à voir le design...
