### ISSUE TITLE
Code pour crédits défilants

### ISSUE THREAD

**Issue by PancakeProphet** [Umi130/Passion-IA#4]
Comme au cinéma pour lister les remerciements par scénario

**Comment by PancakeProphet** [comment]
Maybe use this? https://www.jqueryscript.net/animation/Create-Scrolling-Movie-End-Credits-For-Webpage-Using-jQuery.html

**Comment by julesbonnard** [comment]
ah carrément ! ^^
Je suggérerai plutot de créer un composant vue appelé RollingCredits ou quelque chose comme ça, et d'utiliser les transitions vue CSS, avec ceci => https://codepen.io/oknoblich/pen/vfJxr

Je m'en occupe asap
