### ISSUE TITLE
Système de "points": variable Integer jetable pour mini-jeux

### ISSUE THREAD

**Issue by PancakeProphet** [Umi130/Passion-IA#5]
Avoir une variable "jetable" que l'on peut incrémenter pour les mini-jeux (style "si plus de 3 bonnes réponses" "sinon", remise à zéro à chaque nouveau jeu)

**Comment by julesbonnard** [comment]
Pas compris... quel est la finalité recherchée ?

**Comment by PancakeProphet** [comment]
Par exemple, pour le chemin "musicien", il y a différents mini-jeux :

- Reconnaître les instruments (3 points possibles)
- Reconnaître les partitions (3 points possibles), puis reconnaître le début & fin d'une partitions (2 points possibles)

A la fin de ces "mini-jeux", en fonction du nombre de "points", si >, afficher un message "bravo, suffisamment de bonnes réponses", si <, afficher un message différent.

Vu qu'il y a plusieurs mini-jeux, une solution qui me semble possible est d'incrémenter une variable "minijeu_points" si le choix est bon, et une fois la phase mini-jeu terminée,
- utiliser when: minijeu_points >= X pour afficher le bon message, puis
- remettre la variable à zéro quand le message apparaît en cas de prochain mini-jeu.

Je ne sais pas si c'est bien expliqué...
