### ISSUE TITLE
Profil conducteur - Jeu oui/non: code à améliorer

### ISSUE THREAD

**Issue by PancakeProphet** [Umi130/Passion-IA#6]
Va nécessiter un nouveau code .vue!

EDIT yesno.vue implémenté, à améliorer (boutons non-fonctionnels & score non incrémenté)

**Comment by julesbonnard** [comment]
Surement. Mais quelle différence avec l'outil choices et deux réponses OUI et NON ??

**Comment by PancakeProphet** [comment]
A la fois pour
- différencier l'interactivité avec les autres parcours pour éviter la lassitude
- le swipe a quelque chose de naturel, "à la tinder"

Il y aurait deux "mini-jeux" basés sur ce principe, avec une présentation séquentielle de cinq à dix images :
**Est-ce une photo d’un passage piéton ? << non  oui >>**

**Les gens sont-ils sur la route ? << non  oui >>.** 

_ou_ On pourrait bien sûr, si c'est plus simple, avoir

**Question** (comme pour choices)
____________________________________

Une grande image


____________________________________
 Non (bouton rouge)  Oui (bouton vert)

Ce qui nécessiterait peut-être moins de travail?

**Comment by PancakeProphet** [comment]
Prototypage vite fait mal fait 👍 

https://ibb.co/igJs7H

**Comment by PancakeProphet** [comment]
Les boutons Oui / Non sont là, ainsi qu'une image grand format.

Reste à
-passer à l'étape d'après OnClick
-incrémenter (ou non) le score en fonction de la bonne réponse

**Comment by julesbonnard** [comment]
Bravo pour l'implémentation. J'ai ajouté la validation quand on clique sur oui ou non, et le décompte des points. Reste à savoir ce que vous voulez faire de ceux là.
